import test from 'node:test';
import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {readFileSync} from 'node:fs';
import {Keypair,SystemProgram,TransactionMessage,VersionedTransaction} from '@solana/web3.js';
import {env} from './mock-env';
import {toAtomic,fromAtomic,SOL,USDC} from '../lib/swap-shared';
import {transactionMessage,verifySignedTransaction} from '../lib/transaction';
import {createOrder,executeOrder,orderStatus,authorize,rateLimit,configuration} from '../lib/swap-server';
const sqlite=new DatabaseSync(':memory:');for(const f of ['0000_certain_invisible_woman.sql','0001_secret_whistler.sql'])sqlite.exec(readFileSync(`drizzle/${f}`,'utf8'));
env.DB={prepare(sql:string){let args:any[]=[];return{bind(...a:any[]){args=a;return this},async first(){return sqlite.prepare(sql).get(...args)||null},async run(){const r=sqlite.prepare(sql).run(...args);return{meta:{changes:Number(r.changes)}}}}}};
const signer=Keypair.generate(),other=Keypair.generate();
function transaction(lamports=100){return new VersionedTransaction(new TransactionMessage({payerKey:signer.publicKey,recentBlockhash:Keypair.generate().publicKey.toBase58(),instructions:[SystemProgram.transfer({fromPubkey:signer.publicKey,toPubkey:other.publicKey,lamports})]}).compileToV0Message())}
const referral=Keypair.generate().publicKey.toBase58();env.JUPITER_API_KEY='test';env.JUPITER_REFERRAL_ACCOUNT=referral;env.PEAK_TRADING_ENABLED='true';env.PEAK_API_KEY='test-only-integration-key';
const payload={inputMint:SOL,outputMint:USDC,amount:'100000000',taker:signer.publicKey.toBase58(),slippageBps:100};
let nextQuote:any,executeCount=0,executeMode='success';
function prepareQuote(extra:any={}){const tx=transaction();nextQuote={...payload,inAmount:payload.amount,outAmount:'12000000',otherAmountThreshold:'11880000',transaction:Buffer.from(tx.serialize()).toString('base64'),requestId:crypto.randomUUID(),referralAccount:referral,feeBps:125,feeMint:SOL,priceImpact:0.2,prioritizationFeeLamports:50000,router:'metis',...extra};return tx}
const realFetch=globalThis.fetch;
globalThis.fetch=async(url:any,options:any)=>{if(String(url).includes('/order?')){const params=new URL(String(url)).searchParams;assert.equal(params.get('referralFee'),'125');assert.equal(params.get('referralAccount'),referral);assert.equal(params.get('receiver'),null);return Response.json(nextQuote)}executeCount++;if(executeMode==='timeout')throw Error('timeout');return Response.json({status:'Success',code:0,signature:'test-signature',totalInputAmount:'100000000',totalOutputAmount:'12000000'})};
function signed(tx:VersionedTransaction){tx.sign([signer]);return Buffer.from(tx.serialize()).toString('base64')}
await test('Atomic units preserve precision and reject invalid inputs',()=>{assert.equal(toAtomic('0.000000001',9),'1');assert.equal(toAtomic('9007199254.740993',6),'9007199254740993');assert.equal(fromAtomic('1000000000',9),'1');for(const value of ['-1','1e5','0','1.0000000001'])assert.throws(()=>toAtomic(value,9));assert.throws(()=>toAtomic('18446744073709551616',0))});
await test('Valid wallet signature accepted; altered messages and unsigned payloads rejected',async()=>{const tx=transaction();const message=transactionMessage(Buffer.from(tx.serialize()).toString('base64'));await assert.rejects(verifySignedTransaction(Buffer.from(tx.serialize()).toString('base64'),message,signer.publicKey.toBase58()));await verifySignedTransaction(signed(tx),message,signer.publicKey.toBase58());await assert.rejects(verifySignedTransaction(signed(transaction(999)),message,signer.publicKey.toBase58()))});
await test('Server blocks missing configuration, fee bypass and unsafe quotes',async()=>{env.PEAK_TRADING_ENABLED='false';assert.equal(configuration().ready,false);await assert.rejects(createOrder(payload),(e:any)=>e.code==='SETUP_REQUIRED');env.PEAK_TRADING_ENABLED='true';for(const extra of [{feeBps:10},{referralAccount:other.publicKey.toBase58()},{slippageBps:501},{priceImpact:11},{prioritizationFeeLamports:1000001},{inputMint:USDC}]){prepareQuote(extra);await assert.rejects(createOrder(payload))}prepareQuote();await assert.rejects(createOrder({...payload,referralFee:0}));await assert.rejects(createOrder({...payload,amount:'-1'}))});
await test('Successful swap is stored; duplicate execution returns same result without resubmitting',async()=>{const tx=prepareQuote();const order=await createOrder(payload);const before=executeCount;const body={id:order.id,signedTransaction:signed(tx)};assert.equal((await executeOrder(body)).status,'confirmed');assert.equal((await executeOrder(body)).status,'confirmed');assert.equal(executeCount,before+1);assert.equal((await orderStatus(order.id)).status,'confirmed')});
await test('Expired orders cannot be submitted',async()=>{const tx=prepareQuote();const order=await createOrder(payload);sqlite.prepare('UPDATE swap_orders SET expires_at=0 WHERE id=?').run(order.id);await assert.rejects(executeOrder({id:order.id,signedTransaction:signed(tx)}),(e:any)=>e.code==='QUOTE_EXPIRED')});
await test('Timeout stays unknown and only identical signed transaction is retried',async()=>{const tx=prepareQuote();const order=await createOrder(payload);const body={id:order.id,signedTransaction:signed(tx)};executeMode='timeout';await assert.rejects(executeOrder(body));assert.equal((await orderStatus(order.id)).status,'unknown');await assert.rejects(executeOrder({id:order.id,signedTransaction:signed(transaction(222))}));executeMode='success';assert.equal((await executeOrder(body)).status,'confirmed')});
await test('Concurrent executions produce only one upstream submission',async()=>{const tx=prepareQuote();const order=await createOrder(payload);const body={id:order.id,signedTransaction:signed(tx)},before=executeCount;const results=await Promise.allSettled([executeOrder(body),executeOrder(body)]);assert.ok(results.some(r=>r.status==='fulfilled'));assert.equal(executeCount,before+1)});
await test('Origin checks and bearer authorization reject outsiders',async()=>{await assert.rejects(authorize(new Request('https://peak.test/api/v1/orders',{method:'POST',headers:{Origin:'https://evil.test'}}),true));await assert.rejects(authorize(new Request('https://peak.test/api/v1/orders',{method:'POST'}),true));await assert.rejects(authorize(new Request('https://peak.test/api/v1/orders',{method:'POST',headers:{Authorization:'Bearer wrong'}}),true));assert.equal(await authorize(new Request('https://peak.test/api/v1/orders',{method:'POST',headers:{Authorization:'Bearer test-only-integration-key'}}),true),'integration')});
await test('Rate limit is persisted and enforced',async()=>{const req=new Request('https://peak.test/api/v1/orders',{headers:{'cf-connecting-ip':'192.0.2.1'}});await rateLimit(req,'test',1);await assert.rejects(rateLimit(req,'test',1),(e:any)=>e.status===429)});
globalThis.fetch=realFetch;sqlite.close();
