// Checks Peak's hand-written venue instructions and account decoders against
// reference output from each venue's official SDK (tests/fixtures/venues.json,
// generated by scripts/venue-fixtures.cjs; SDK versions are recorded in the file).
import test from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { PublicKey, TransactionInstruction } from '@solana/web3.js';
import { SOL_MINT, TOKEN_PROGRAM, TOKEN_2022_PROGRAM, type Account } from '../lib/solana';
import { pumpCurveBuy, pumpCurveSell, pumpAmmBuy, pumpAmmSell, pumpAmmExtendPool, decodePumpPool, decodePumpGlobalRecipients, decodePumpAmmRecipients, discoverPump, PUMP, AMM, PUMP_PROGRAM, PUMP_AMM_PROGRAM } from '../lib/venues/pump';
import { decodeCpmm, cpmmSwap, decodeAmmV4, ammV4Swap } from '../lib/venues/raydium';
import { shortlist } from '../lib/router';
import type { Route } from '../lib/venues/types';
import { decodeDamm, dammSwap, decodeLbPair, binArraysForSwap, dlmmSwap } from '../lib/venues/meteora';

const f = JSON.parse(readFileSync('tests/fixtures/venues.json', 'utf8'));
type Ix = { programId: string; keys: [string, boolean, boolean][]; data: string };
const K = (s: string) => new PublicKey(s);
const { user, mint, creator, feeRecipient, buyback, pool } = Object.fromEntries(Object.entries(f.keys as Record<string, string>).map(([k, v]) => [k, K(v)]));
const bytes = (name: string) => new Uint8Array(Buffer.from(f.accounts[name], 'base64'));
const shape = (i: TransactionInstruction): Ix => ({ programId: i.programId.toBase58(), keys: i.keys.map(k => [k.pubkey.toBase58(), k.isWritable, k.isSigner]), data: Buffer.from(i.data).toString('hex') });
const venueIx = (list: Ix[], program: PublicKey, minKeys = 20) => list.find(i => i.programId === program.toBase58() && i.keys.length >= minKeys)!;
const BUY_EXACT_SOL_IN = '38fc74089edfcd5f', BUY_EXACT_QUOTE_IN = 'c62e1552b4d9e870';
/** Same accounts and arguments; only the discriminator differs (exact-in variant of the SDK's `buy`). */
function sameExceptDiscriminator(mine: TransactionInstruction, ref: Ix, discriminator: string) {
  const m = shape(mine);
  assert.deepEqual(m.keys, ref.keys); assert.equal(m.programId, ref.programId);
  assert.equal(m.data.slice(0, 16), discriminator); assert.equal(m.data.slice(16), ref.data.slice(16));
}
const acct = (data: Uint8Array, owner: PublicKey): Account => ({ data, owner: owner.toBase58(), lamports: 1 });
const args = { amountIn: BigInt(1000), minOut: BigInt(2000) };

await test('Pump.fun curve buy/sell match @pump-fun/pump-sdk account lists', () => {
  for (const [tag, tokenProgram] of [['t22', TOKEN_2022_PROGRAM], ['spl', TOKEN_PROGRAM]] as const) {
    const common = { user, mint, creator, tokenProgram, feeRecipient, buybackFeeRecipient: buyback, isMayhemMode: false };
    sameExceptDiscriminator(pumpCurveBuy({ ...common, isCashbackCoin: false, spendableSolIn: BigInt(1000), minTokensOut: BigInt(2000) }), f.instructions[`pumpBuy_${tag}`], BUY_EXACT_SOL_IN);
    for (const cashback of [false, true]) assert.deepEqual(shape(pumpCurveSell({ ...common, isCashbackCoin: cashback, amount: BigInt(1000), minSolOutput: BigInt(2000) })), f.instructions[`pumpSell_${tag}_${cashback ? 'cashback' : 'plain'}`]);
  }
});

await test('Pump.fun global and curve accounts decode at IDL offsets', async () => {
  const global = bytes('pumpGlobal'), first = () => 0;
  assert.deepEqual(Object.values(decodePumpGlobalRecipients(global, false, first)).map(String), [feeRecipient.toBase58(), f.keys.buybackList0]);
  const mayhem = decodePumpGlobalRecipients(global, true, first);
  assert.notEqual(mayhem.feeRecipient.toBase58(), feeRecipient.toBase58());
  // Discovery reads the curve, applies it to the builder and reports SOL-side liquidity.
  const rpc = { getAccounts: async (ks: PublicKey[]) => ks.map(k => k.equals(PUMP.global) ? acct(global, PUMP_PROGRAM) : k.equals(PUMP.bondingCurve(mint)) ? acct(bytes('pumpCurve'), PUMP_PROGRAM) : null), getProgramAccounts: async () => [] };
  const [route] = await discoverPump({ rpc, side: 'sell', mint, mintProgram: TOKEN_2022_PROGRAM, user, pick: first });
  assert.equal(route.venue, 'pump-curve'); assert.equal(route.liquidity, BigInt(333)); assert.deepEqual(route.output, { kind: 'lamports' });
  const [sell] = route.instructions(args);
  assert.equal(sell.keys[8].pubkey.toBase58(), PUMP.creatorVault(creator).toBase58()); // curve creator
  assert.equal(sell.keys[14].pubkey.toBase58(), PUMP.userVolumeAccumulator(user).toBase58()); // cashback coin
  assert.equal(sell.keys[1].pubkey.toBase58(), mayhem.feeRecipient.toBase58()); // mayhem-mode curve uses reserved recipients
});

await test('PumpSwap buy/sell/extend match @pump-fun/pump-swap-sdk', () => {
  for (const tag of ['plain_creator', 'cashback_creator_extend', 'plain_nocreator']) {
    const [cashback, creatorTag] = tag.split('_');
    const decoded = decodePumpPool(pool, bytes(`ammPool_${cashback === 'cashback'}_${creatorTag}`));
    const p = { ...decoded, needsExtend: tag.endsWith('extend'), user, baseTokenProgram: TOKEN_2022_PROGRAM, protocolFeeRecipient: feeRecipient, buybackFeeRecipient: buyback };
    const buyRef = f.instructions[`ammBuy_${tag}`] as Ix[], sellRef = f.instructions[`ammSell_${tag}`] as Ix[];
    sameExceptDiscriminator(pumpAmmBuy({ ...p, spendableQuoteIn: BigInt(1000), minBaseAmountOut: BigInt(2000) }), venueIx(buyRef, PUMP_AMM_PROGRAM), BUY_EXACT_QUOTE_IN);
    assert.deepEqual(shape(pumpAmmSell({ ...p, baseAmountIn: BigInt(1000), minQuoteAmountOut: BigInt(2000) })), venueIx(sellRef, PUMP_AMM_PROGRAM));
    if (p.needsExtend) assert.deepEqual(shape(pumpAmmExtendPool(pool, user)), buyRef[0]);
  }
  const first = () => 0, cfg = bytes('ammGlobalConfig');
  assert.equal(decodePumpAmmRecipients(cfg, false, first).protocolFeeRecipient.toBase58(), f.keys.ammProtocol0);
  assert.equal(decodePumpAmmRecipients(cfg, false, first).buybackFeeRecipient.toBase58(), f.keys.ammBuyback0);
  assert.equal(AMM.canonicalPool(mint).toBase58(), f.keys.canonicalPool);
});

await test('Raydium CPMM and AMM v4 match @raydium-io/raydium-sdk-v2', () => {
  const cp = decodeCpmm(pool, bytes('cpmmPool'));
  assert.deepEqual(shape(cpmmSwap({ ...cp, user, inputMint: SOL_MINT, amountIn: BigInt(1000), minOut: BigInt(2000) })), f.instructions.cpmmBuy);
  assert.deepEqual(shape(cpmmSwap({ ...cp, user, inputMint: mint, amountIn: BigInt(1000), minOut: BigInt(2000) })), f.instructions.cpmmSell);
  const v4 = decodeAmmV4(pool, bytes('ammV4Pool'));
  assert.deepEqual(shape(ammV4Swap({ ...v4, user, inputMint: mint, amountIn: BigInt(1000), minOut: BigInt(2000) })), f.instructions.ammV4Sell);
});

await test('Meteora DAMM v2 and DLMM match the Meteora SDK programs', () => {
  const damm = decodeDamm(pool, bytes('dammPool'));
  assert.deepEqual(shape(dammSwap({ ...damm, user, inputMint: SOL_MINT, amountIn: BigInt(1000), minOut: BigInt(2000) })), f.instructions.dammBuy);
  const lb = decodeLbPair(pool, bytes('lbPair'));
  assert.equal(lb.activeId, -5);
  assert.deepEqual(binArraysForSwap(lb, true).map(String), f.binArrays.swapForY);
  assert.deepEqual(binArraysForSwap(lb, false).map(String), f.binArrays.swapForX);
  const binArrays = binArraysForSwap(lb, false);
  assert.deepEqual(shape(dlmmSwap({ ...lb, user, inputMint: SOL_MINT, amountIn: BigInt(1000), minOut: BigInt(2000), binArrays })), f.instructions.dlmmBuy_noext);
  assert.deepEqual(shape(dlmmSwap({ ...lb, user, inputMint: SOL_MINT, amountIn: BigInt(1000), minOut: BigInt(2000), binArrays, bitmapExtension: K(f.keys.bitmapExtension) })), f.instructions.dlmmBuy_ext);
});

await test('Router shortlists the deepest pools, at most two per venue', async () => {
  const r = (venue: Route['venue'], liquidity: number) => ({ venue, pool: venue + liquidity, liquidity: BigInt(liquidity), output: { kind: 'lamports' as const }, instructions: () => [] }) as Route;
  const picked = shortlist([r('raydium-cpmm', 5), r('raydium-cpmm', 9), r('raydium-cpmm', 7), r('meteora-dlmm', 0), r('pumpswap', 1)]);
  assert.deepEqual(picked.map(p => p.pool), ['raydium-cpmm9', 'raydium-cpmm7', 'pumpswap1']);
});
