'use client';
import {useEffect,useRef,useState} from 'react';
import {VersionedTransaction} from '@solana/web3.js';
import {ArrowDown,ArrowUpRight,Check,ChevronDown,Copy,ExternalLink,Loader2,ShieldCheck,SlidersHorizontal,Wallet,X,Zap,Code2,TriangleAlert} from 'lucide-react';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Checkbox} from '@/components/ui/checkbox';
import {Tabs,TabsList,TabsTrigger} from '@/components/ui/tabs';
import {DEFAULT_TOKENS,Token,SOL,toAtomic,fromAtomic,short} from '@/lib/swap-shared';
type Provider={publicKey?:{toString():string};connect():Promise<{publicKey:{toString():string}}>;disconnect():Promise<void>;signTransaction(tx:VersionedTransaction):Promise<VersionedTransaction>;on?:(event:string,fn:(key:any)=>void)=>void;removeListener?:(event:string,fn:(key:any)=>void)=>void};
type Quote={id:string;expiresAt:number;transaction:string;quote:{inAmount:string;outAmount:string;minimumReceived:string;priceImpactPct:number;slippageBps:number;venueLabel:string;feeLamports:string;totalInputAmount:string;signatureFeeLamports:number;prioritizationFeeLamports:number}};
type Health={ready:boolean;missing:string[];externalApiConfigured:boolean};
async function api(path:string,body?:unknown){const r=await fetch(`/api/v1/${path}`,{method:body?'POST':'GET',headers:{'Content-Type':'application/json'},...(body?{body:JSON.stringify(body)}:{})});const d:any=await r.json();if(!r.ok)throw Error(d.error?.message||'Request failed.');return d;}
const FINAL=['confirmed','failed','expired','rejected'];
const toBase64=(bytes:Uint8Array)=>btoa(Array.from(bytes,c=>String.fromCharCode(c)).join(''));
export default function Home(){
 const [input,setInput]=useState<Token>(DEFAULT_TOKENS[0]),[output,setOutput]=useState<Token>(DEFAULT_TOKENS[1]),[amount,setAmount]=useState(''),[slippage,setSlippage]=useState(100),[wallet,setWallet]=useState(''),[provider,setProvider]=useState<Provider|null>(null),[health,setHealth]=useState<Health|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(''),[quote,setQuote]=useState<Quote|null>(null),[result,setResult]=useState<any>(null),[now,setNow]=useState(Date.now()),[picker,setPicker]=useState<'input'|'output'|null>(null),[walletDialog,setWalletDialog]=useState(false),[settings,setSettings]=useState(false),[search,setSearch]=useState(''),[found,setFound]=useState<Token[]>(DEFAULT_TOKENS),[searching,setSearching]=useState(false),[searchError,setSearchError]=useState(''),[source,setSource]=useState(''),[copied,setCopied]=useState(false),[ack,setAck]=useState(false);
 const revision=useRef(0),signed=useRef<{id:string;signedTransaction:string}|null>(null),busyRef=useRef(false);
 function invalidate(){revision.current++;setQuote(null);setResult(null);setError('');setAck(false)}
 useEffect(()=>{const pending=sessionStorage.getItem('peak-pending-order');if(pending)api(`orders/${pending}`).then(d=>{setResult(d.result||d);if(FINAL.includes(d.status))sessionStorage.removeItem('peak-pending-order')}).catch(()=>setError('A previous trade needs a status check.'));api('health').then(setHealth).catch(()=>setError('Unable to reach Peak. Please reload.'));const timer=setInterval(()=>setNow(Date.now()),1000);const p=new URLSearchParams(location.search);const src=p.get('ref');if(src&&/^[\w-]{1,64}$/.test(src))setSource(src);const mint=p.get('outputMint')||p.get('token');if(mint)api(`tokens?query=${encodeURIComponent(mint)}`).then(d=>{const t=d.tokens.find((x:Token)=>x.id===mint);if(t){setOutput(t);if(t.id===SOL)setInput(DEFAULT_TOKENS[1])}else setError('This token could not be found. Check the mint address.')}).catch(e=>setError(e.message));return()=>clearInterval(timer)},[]);
 useEffect(()=>{if(!provider)return;const changed=(key:any)=>{setWallet(key?.toString()||'');invalidate()};const disconnected=()=>changed(null);provider.on?.('accountChanged',changed);provider.on?.('disconnect',disconnected);return()=>{provider.removeListener?.('accountChanged',changed);provider.removeListener?.('disconnect',disconnected)}},[provider]);
 useEffect(()=>{if(!picker)return;let active=true;setSearchError('');if(!search.trim()){setFound(DEFAULT_TOKENS);setSearching(false);return}setSearching(true);const timer=setTimeout(()=>{api(`tokens?query=${encodeURIComponent(search.trim())}`).then(d=>{if(active)setFound(d.tokens)}).catch(e=>{if(active){setFound([]);setSearchError(e.message)}}).finally(()=>{if(active)setSearching(false)})},450);return()=>{active=false;clearTimeout(timer)}},[search,picker]);
 const remaining=quote?Math.max(0,Math.ceil((quote.expiresAt-now)/1000)):0;
 async function connect(name:string){setError('');try{const w=window as any;const p:Provider=name==='Phantom'?w.phantom?.solana:w.solflare;if(!p){setError(`Open Peak inside ${name}'s browser on mobile, or install its browser extension.`);return}const r=await p.connect();setProvider(p);setWallet(r.publicKey.toString());setWalletDialog(false);invalidate()}catch(e:any){setError(e.message||'Wallet connection cancelled.')}}
 async function getQuote(){if(busyRef.current)return;setError('');if(!wallet){setWalletDialog(true);return}const version=revision.current;busyRef.current=true;setBusy('Finding route');setQuote(null);setResult(null);signed.current=null;try{const d=await api('orders',{inputMint:input.id,outputMint:output.id,amount:toAtomic(amount,input.decimals),taker:wallet,slippageBps:slippage,...(source?{source}:{})});if(version===revision.current){setQuote(d);setNow(Date.now());setAck(false)}}catch(e:any){setError(e.message)}finally{setBusy('');busyRef.current=false}}
 async function submit(){if(!quote||!provider||remaining===0||busyRef.current)return;busyRef.current=true;setBusy('Approve in your wallet');setError('');const current=quote,version=revision.current;try{const tx=VersionedTransaction.deserialize(Uint8Array.from(atob(current.transaction),c=>c.charCodeAt(0)));const original=toBase64(tx.message.serialize());const sign=await provider.signTransaction(tx);if(version!==revision.current||provider.publicKey?.toString()!==wallet)throw Error('Wallet or swap changed. Request a fresh quote.');if(toBase64(sign.message.serialize())!==original)throw Error('Wallet returned an altered transaction.');if(Date.now()>=current.expiresAt)throw Error('Quote expired while signing. Request a fresh quote.');signed.current={id:current.id,signedTransaction:toBase64(sign.serialize())};sessionStorage.setItem('peak-pending-order',current.id);setBusy('Confirming on Solana');const d=await api('execute',signed.current);setResult(d);if(FINAL.includes(d.status))sessionStorage.removeItem('peak-pending-order');setQuote(null)}catch(e:any){setError(e.message);if(signed.current){setResult({status:'unknown',id:current.id});setQuote(null)}}finally{busyRef.current=false;setBusy('')}}
 async function checkStatus(){if(!result?.id)return;setBusy('Checking confirmation');try{const d=await api(`orders/${result.id}`);setResult(d.result||d);if(FINAL.includes(d.status))sessionStorage.removeItem('peak-pending-order');setError('')}catch(e:any){setError(e.message)}finally{setBusy('')}}
 async function retrySame(){if(!signed.current)return;setBusy('Checking the same transaction');try{const d=await api('execute',signed.current);setResult(d);if(FINAL.includes(d.status))sessionStorage.removeItem('peak-pending-order');setError('')}catch(e:any){setError(e.message)}finally{setBusy('')}}
 function choose(t:Token){invalidate();if(picker==='input'){if(t.id===output.id)setOutput(input);setInput(t)}else{if(t.id===input.id)setInput(output);setOutput(t)}setPicker(null);setSearch('')}
 function share(){const u=new URL(location.origin);u.searchParams.set('outputMint',output.id);if(source)u.searchParams.set('ref',source);navigator.clipboard.writeText(u.toString()).then(()=>{setCopied(true);setTimeout(()=>setCopied(false),2000)}).catch(()=>setError('Unable to copy the link.'))}
 const unverified=!output.isVerified||!input.isVerified;
 return <div className="app-shell"><header className="topbar"><a className="brand" href="/" aria-label="Peak Swap home"><span className="brand-icon"><Zap size={22} fill="currentColor"/></span>PEAK<span className="brand-product">SWAP</span></a><nav><a className="nav-active" href="/">Swap</a><a href="/developers">Developers <ArrowUpRight size={14}/></a></nav><button className="wallet-button" onClick={()=>wallet?provider?.disconnect().then(()=>{setWallet('');invalidate()}):setWalletDialog(true)}><Wallet size={16}/>{wallet?short(wallet):'Connect wallet'}</button></header>
 <main className="workspace"><div className="page-heading"><span className="eyebrow">SOLANA / MAINNET</span><div className="heading-row"><h1>Your next move.</h1><span className="powered">Direct to <strong>Pump.fun · Raydium · Meteora</strong></span></div></div>
 <div className="swap-layout"><section className="swap-card" aria-label="Swap tokens"><div className="card-top"><h2>Swap</h2><button className="icon-button" aria-label="Slippage settings" onClick={()=>setSettings(true)}><SlidersHorizontal size={19}/></button></div>
 <fieldset disabled={!!busy||['unknown','executing'].includes(result?.status)} className="swap-fields"><div className="asset-box"><label htmlFor="amount">You pay</label><div className="asset-line"><input id="amount" inputMode="decimal" autoComplete="off" placeholder="0.00" value={amount} onChange={e=>{setAmount(e.target.value);invalidate()}}/><button className="token-button" onClick={()=>{setPicker('input');setSearch('');setSearching(false)}}><span className={'token-icon '+(input.id===SOL?'sol':'usd')}>{input.symbol.slice(0,1)}</span>{input.symbol}<ChevronDown size={16}/></button></div><span className="asset-caption">{input.name}</span></div>
 <div className="reverse-row"><button className="reverse" aria-label="Reverse token pair" onClick={()=>{setInput(output);setOutput(input);setAmount('');invalidate()}}><ArrowDown size={18}/></button></div>
 <div className="asset-box receive"><span className="field-label">You receive</span><div className="asset-line"><div className={'receive-amount '+(!quote?'muted':'')}>{quote?Number(fromAtomic(quote.quote.outAmount,output.decimals)).toLocaleString(undefined,{maximumFractionDigits:8}):'0.00'}</div><button className="token-button" onClick={()=>{setPicker('output');setSearch('');setSearching(false)}}><span className={'token-icon '+(output.id===SOL?'sol':'usd')}>{output.symbol.slice(0,1)}</span>{output.symbol}<ChevronDown size={16}/></button></div><span className="asset-caption">{quote?'Estimated output · includes swap fee':output.name}</span></div></fieldset>
 <div className="compact-details"><div><span>Swap fee</span><span>1% <span className="muted">Peak, in SOL</span></span></div><div><span>Slippage tolerance</span><button onClick={()=>setSettings(true)}>{(slippage/100).toFixed(1)}%</button></div></div>
 {health&&!health.ready&&<div className="notice"><TriangleAlert size={17}/><div><strong>Trading opens after setup</strong><p>Peak’s Solana RPC endpoint and fee wallet need activation.</p><a href="/developers#activation">View setup details <ArrowUpRight size={13}/></a></div></div>}
 {error&&<div role="alert" className="error-message">{error}</div>}
 {quote&&<div className="quote-review"><div className="review-top"><strong>Review your swap</strong><span className={remaining<10?'warning-text':''}>{remaining?`${remaining}s remaining`:'Quote expired'}</span></div><dl><div><dt>Route</dt><dd>{quote.quote.venueLabel}</dd></div><div><dt>Minimum received</dt><dd>{fromAtomic(quote.quote.minimumReceived,output.decimals)} {output.symbol}</dd></div><div><dt>Peak fee (1%)</dt><dd>{fromAtomic(quote.quote.feeLamports,9)} SOL</dd></div>{input.id===SOL&&<div><dt>Total SOL spent</dt><dd>{fromAtomic(quote.quote.totalInputAmount,9)} SOL</dd></div>}<div><dt>Price impact</dt><dd>{(quote.quote.priceImpactPct*100).toFixed(2)}%</dd></div><div><dt>Network fee</dt><dd>{((quote.quote.signatureFeeLamports+quote.quote.prioritizationFeeLamports)/1e9).toFixed(6)} SOL <span className="muted">+ rent for new token accounts</span></dd></div></dl>{unverified&&<label className="risk-ack"><Checkbox checked={ack} onCheckedChange={v=>setAck(v===true)} aria-label="Acknowledge unverified token risk"/>I checked the token address. Unverified tokens can lose all value.</label>}</div>}
 {result&&<div className={'result '+(result.status==='confirmed'?'success':'')} role="status"><strong>{result.status==='confirmed'?'Swap confirmed':result.status==='failed'?'Swap failed on-chain':['rejected','expired'].includes(result.status)?'Swap was not sent':'Confirmation pending'}</strong><p>{result.status==='confirmed'?'Your tokens are in your wallet.':result.error||'Check this transaction before starting another trade.'}</p>{result.signature&&<a href={`https://solscan.io/tx/${result.signature}`} target="_blank" rel="noreferrer">View transaction <ExternalLink size={14}/></a>}{['unknown','executing'].includes(result.status)&&<div className="result-actions"><button onClick={checkStatus} disabled={!!busy}>Check status</button>{signed.current&&<button onClick={retrySame} disabled={!!busy}>Retry same transaction</button>}</div>}</div>}
 {quote&&remaining>0?<button className="primary-button" disabled={!!busy||(unverified&&!ack)} onClick={submit}>{busy?<><Loader2 className="spin" size={18}/>{busy}</>:<>Confirm swap <ArrowUpRight size={19}/></>}</button>:<button className="primary-button" disabled={!!busy||(!!wallet&&(!health?.ready||!amount))||['unknown','executing'].includes(result?.status)} onClick={getQuote}>{busy?<><Loader2 className="spin" size={18}/>{busy}</>:!wallet?'Connect wallet':!health?.ready?'Trading not active':quote?'Refresh quote':'Get quote'}{!busy&&<ArrowUpRight size={20}/>}</button>}
 <p className="wallet-note"><ShieldCheck size={15}/>You sign. Your wallet stays in your control.</p></section>
 <aside className="context-panel"><div className="context-intro"><span className="eyebrow accent">ONE SWAP. MORE ROUTES.</span><h2>From the first trade<br/>to the next chapter.</h2><p>Peak trades straight against the pools themselves. Every quote simulates each candidate pool on-chain and takes the best.</p></div><div className="route-stages"><div><span className="stage-number">01</span><div><h3>Before migration</h3><p>Pump.fun bonding curves.<br/>Availability checked with every quote.</p></div></div><div><span className="stage-number">02</span><div><h3>After migration</h3><p>PumpSwap, Raydium (CPMM, AMM v4) and Meteora (DAMM v2, DLMM) SOL pools.</p></div></div></div><div className="fee-breakdown"><span className="eyebrow">CLEAR FROM THE START</span><div><span>Peak</span><strong>1.00%</strong></div><div><span>Pool fees</span><strong>In quote</strong></div><p>Peak’s fee is charged in SOL: on top of what you spend when buying, from the proceeds when selling. Network costs are separate. Your quote shows the final estimate before you sign.</p></div><button className="share-button" onClick={share}>{copied?<Check size={16}/>:<Copy size={16}/>} {copied?'Buy link copied':'Copy buy link for '+output.symbol}<ArrowUpRight size={15}/></button></aside></div>
 <div className="bottom-strip"><span><ShieldCheck size={16}/>Wallet-signed transactions</span><span><Zap size={16}/>Direct pool execution</span><a href="/developers"><Code2 size={16}/>Build with Peak <ArrowUpRight size={14}/></a></div></main><footer><span>PEAK / SWAP</span><span>Trade with intent.</span><a href="/developers#coverage">Routing & limitations</a></footer>
 <Dialog open={!!picker} onOpenChange={v=>{if(!v)setPicker(null)}}><DialogContent className="peak-dialog"><DialogTitle>Select a token</DialogTitle><DialogDescription>Paste the token’s mint address. Every swap is paired with SOL.</DialogDescription><input className="search-input" aria-label="Search tokens" placeholder="Paste mint address" value={search} onChange={e=>setSearch(e.target.value)} autoFocus/><div className="token-results">{searching?<div className="search-state"><Loader2 className="spin"/>Looking up token…</div>:searchError?<p role="alert">{searchError}</p>:found.length?found.map(t=><button className="token-result" key={t.id} onClick={()=>choose(t)}><span className={'token-icon '+(t.id===SOL?'sol':'usd')}>{t.symbol.slice(0,1)}</span><span><strong>{t.symbol} {t.isVerified&&<Check size={13}/>}</strong><small>{t.name}</small><small className="token-address">{t.id}</small></span></button>):<p>No token found at that address.</p>}</div></DialogContent></Dialog>
 <Dialog open={walletDialog} onOpenChange={setWalletDialog}><DialogContent className="peak-dialog"><DialogTitle>Connect your wallet</DialogTitle><DialogDescription>Peak never asks for your seed phrase or private key. On mobile, open this page in your wallet’s browser.</DialogDescription><button className="wallet-choice" onClick={()=>connect('Phantom')}><Wallet/>Phantom<ArrowUpRight/></button><button className="wallet-choice" onClick={()=>connect('Solflare')}><Wallet/>Solflare<ArrowUpRight/></button>{error&&<p role="alert" className="error-message">{error}</p>}</DialogContent></Dialog>
 <Dialog open={settings} onOpenChange={setSettings}><DialogContent className="peak-dialog"><DialogTitle>Swap settings</DialogTitle><DialogDescription>Maximum accepted price movement between quote and execution.</DialogDescription><label>Slippage tolerance</label><Tabs value={String(slippage)} onValueChange={v=>{setSlippage(Number(v));invalidate()}}><TabsList className="slippage-options">{[50,100,300,500].map(v=><TabsTrigger key={v} value={String(v)}>{v/100}%</TabsTrigger>)}</TabsList></Tabs><p className="muted">Higher slippage can mean a worse execution price. Peak blocks quotes above 10% price impact and caps priority fees at 0.001 SOL.</p><button className="primary-button" onClick={()=>setSettings(false)}>Done</button></DialogContent></Dialog>
 </div>
}
