import sharp from 'sharp';
import {mkdtemp,writeFile,readFile,rm,access} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join,resolve} from 'node:path';
import {spawn} from 'node:child_process';
import {pathToFileURL} from 'node:url';
import {ContentMachineClient} from './client.mjs';
let stop=false;
process.on('SIGTERM',()=>{stop=true});process.on('SIGINT',()=>{stop=true});
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&apos;'}[c]));
function svgText(text,width,height,colour='#ffffff',size=60){const words=String(text).split(/\s+/);const lines=[''];for(const w of words){if((lines.at(-1)+' '+w).length>Math.floor(width/(size*.58)))lines.push(w);else lines[lines.length-1]+=(lines.at(-1)?' ':'')+w;}return Buffer.from(`<svg xmlns="http://www.w3.org/2000/svg" width="${width}" height="${height}">${lines.slice(0,4).map((line,i)=>`<text x="${width/2}" y="${size+(i*size*1.15)}" font-family="DejaVu Sans,Arial,sans-serif" font-size="${size}" font-weight="bold" fill="${colour}" text-anchor="middle">${esc(line)}</text>`).join('')}</svg>`);}
async function command(bin,args,cwd,timeout=240000){return new Promise((ok,no)=>{const p=spawn(bin,args,{cwd,stdio:['ignore','pipe','pipe'],env:process.env});let out='';p.stdout.on('data',b=>out+=b);p.stderr.on('data',()=>{});const timer=setTimeout(()=>p.kill('SIGKILL'),timeout);p.on('error',e=>{clearTimeout(timer);no(e)});p.on('close',code=>{clearTimeout(timer);code===0?ok(out):no(new Error(`${bin} exited ${code}`))});});}
async function card(image,text,p,w=1080,h=1080){const photo=await sharp(image).resize(w-100,Math.floor(h*.65),{fit:'cover'}).png().toBuffer();return sharp({create:{width:w,height:h,channels:4,background:'#101114'}}).composite([{input:photo,left:50,top:45},{input:svgText(text,w-100,Math.floor(h*.28),p.colour,w===1080?62:48),left:50,top:Math.floor(h*.72)},{input:svgText('$'+p.symbol,w-100,60,'#ffffff',28),left:50,top:h-60}]).png().toBuffer();}
const encoded=(kind,mime,buf)=>({kind,mime,base64:buf.toString('base64')});
export async function render(c,client){const {order:o,job:j}=c,files=[];if(j.kind==='media'){const a=o.assets.find(x=>x.kind==='campaign_image');if(!a)throw new Error('Campaign image missing');const artwork=await client.asset(a.url);for(let i=0;i<8;i++)files.push(encoded('meme_'+i,'image/png',await card(artwork,o.copy.meme_captions[i],o.project)));
const dir=await mkdtemp(join(tmpdir(),'cm-render-'));try{for(const [shape,w,h] of [['square',720,720],['vertical',720,1280]]){const lines=o.copy.trailer_lines.slice(0,4);for(let i=0;i<lines.length;i++){const frame=await card(artwork,lines[i],o.project,w,h);await writeFile(join(dir,`${shape}-${i}.png`),frame);await command(process.env.FFMPEG_PATH||'ffmpeg',['-y','-loop','1','-i',`${shape}-${i}.png`,'-vf',`zoompan=z='min(zoom+0.0008,1.12)':d=90:s=${w}x${h}:fps=24,fade=t=in:st=0:d=0.25,fade=t=out:st=3.5:d=0.25`,'-t','3.75','-c:v','libx264','-preset','veryfast','-crf','25','-pix_fmt','yuv420p',`${shape}-${i}.mp4`],dir);}await writeFile(join(dir,shape+'.txt'),lines.map((_,i)=>`file '${shape}-${i}.mp4'`).join('\n'));await command(process.env.FFMPEG_PATH||'ffmpeg',['-y','-f','concat','-safe','0','-i',shape+'.txt','-c','copy','-movflags','+faststart',shape+'.mp4'],dir);files.push(encoded('trailer_'+shape,'video/mp4',await readFile(join(dir,shape+'.mp4'))));}}finally{await rm(dir,{recursive:true,force:true})}
}else{for(let i=0;i<5;i++){const a=o.assets.find(x=>x.kind==='sticker_art_'+i);if(!a)throw new Error('Sticker artwork missing');const image=await client.asset(a.url);const {data,info}=await sharp(image).resize(512,512,{fit:'contain',background:{r:255,g:0,b:255,alpha:1}}).ensureAlpha().raw().toBuffer({resolveWithObject:true});for(let k=0;k<data.length;k+=4){const r=data[k],g=data[k+1],b=data[k+2];if(r>140&&b>140&&g<130&&Math.min(r,b)-g>75)data[k+3]=0;}let transparent=0;for(let k=3;k<data.length;k+=4)if(data[k]===0)transparent++;if(transparent<512*512*.03||transparent>512*512*.95)throw new Error('Sticker background removal needs review');const png=await sharp(data,{raw:info}).png({palette:true,colours:128,compressionLevel:9}).toBuffer();if(png.length>512000)throw new Error('Sticker exceeds Telegram size limit');files.push(encoded('sticker_png_'+i,'image/png',png));}}await client.request(`render/${j.id}/complete`,{lease:j.lease,files});}
// Binance Square: the article with the campaign image as its cover, via the official post-image.mjs script.
export async function publish(client,run=command){const dir=process.env.BINANCE_SQUARE_SKILL_DIR;if(!dir||!process.env.BINANCE_SQUARE_OPENAPI_KEY)return;await access(join(dir,'scripts/post-image.mjs'));const c=await client.request('publish/claim',{});if(!c)return;let url=null;const tmp=await mkdtemp(join(tmpdir(),'cm-publish-'));try{const a=c.order.assets.find(x=>x.kind==='campaign_image');if(!a)throw new Error('Campaign image missing');const cover=join(tmp,'cover.'+(a.mime==='image/jpeg'?'jpg':a.mime.split('/')[1]));await writeFile(cover,await client.asset(a.url));const output=await run(process.execPath,[resolve(dir,'scripts/post-image.mjs'),'--title',c.order.copy.headline,'--text',c.order.copy.article,'--cover',cover],dir,180000);url=output.match(/https:\/\/(?:www\.)?binance\.com\/[^\s]+/)?.[0]||null;}catch{}finally{await rm(tmp,{recursive:true,force:true})}await client.request(`publish/${c.job.id}/complete`,{lease:c.job.lease,url});}
async function cycle(client){const c=await client.request('render/claim',{});if(c){try{await render(c,client)}catch{await client.request(`render/${c.job.id}/fail`,{lease:c.job.lease,error:'Media rendering failed. Check ffmpeg, available memory and source artwork.'});}}await publish(client);}
if(process.argv[1]&&import.meta.url===pathToFileURL(resolve(process.argv[1])).href){const client=new ContentMachineClient();console.log('Content machine worker started');while(!stop){try{await cycle(client)}catch(e){console.error('Worker cycle failed:',e.message)}if(!stop)await new Promise(r=>setTimeout(r,5000));}console.log('Content machine worker stopped');}
